In [45]:
import pandas as pd
import numpy as np
import altair as alt

In [2]:
def tab_reader(filepathpattern,tabnum,skiprow,low_memory=False):
    tabs = []
    for i in range (tabnum):
        cur_index = i+1
        cur_filepath = filepathpattern.format(cur_index)
        try:
            tab = pd.read_csv(cur_filepath, skiprows=skiprow, low_memory=False)
        except:
            tab = pd.read_csv(cur_filepath, skiprows=skiprow, encoding='latin-1', low_memory=low_memory)
        tabs.append(tab)
    return tabs

In [3]:
# 2017 data
rcbp_2017_mb_revenue_Tabs = tab_reader("../../../data/2017_csv_eng/2017_Medium businesses_Total revenue based_csv/_2017_Eng_Medium_Revenue_Tab{}.csv",5,5)
rcbp_2017_sb_revenue_Tabs = tab_reader("../../../data/2017_csv_eng/2017_Small businesses_Total revenue based_csv/_2017_Small businesses_Total revenue based_Tab{}.csv",7,5)
rcbp_2017_sb_revenue_Tabs[0] = tab_reader("../../../data/2017_csv_eng/2017_Small businesses_Total revenue based_csv/_2017_Small businesses_Total revenue based_Tab{}.csv",1,6)[0]

In [4]:
# 2018 data
rcbp_2018_mb_revenue_Tabs = tab_reader("../../../data/2018_csv_eng/2018_Medium businesses_Total revenue based_csv/_2018_Medium businesses_Total revenue_Tab{}.csv",5,5)
rcbp_2018_sb_revenue_Tabs = tab_reader("../../../data/2018_csv_eng/2018_Small businesses_Total revenue based_csv/_2018_Small businesses_Total revenue_Tab{}.csv",7,5)
rcbp_2018_sb_revenue_Tabs[0] = tab_reader("../../../data/2018_csv_eng/2018_Small businesses_Total revenue based_csv/_2018_Small businesses_Total revenue_Tab{}.csv",1,6)[0]

In [5]:
# 2019 data
rcbp_2019_mb_revenue_Tabs = tab_reader("../../../data/2019_csv_eng/2019_Medium businesses_Total revenue_csv/_2019_Medium businesses_Total revenue_Tab{}.csv",5,5)
rcbp_2019_sb_revenue_Tabs = tab_reader("../../../data/2019_csv_eng/2019_Small businesses_Total revenue_csv/_2019_Small businesses_Total revenue_Tab{}.csv",7,5)
rcbp_2019_sb_revenue_Tabs[0] = tab_reader("../../../data/2019_csv_eng/2019_Small businesses_Total revenue_csv/_2019_Small businesses_Total revenue_Tab{}.csv",1,6)[0]

### 1. Medium business important variables

**'North American Industry Classification System, NAICS - code',**</br> 
**'North American Industry Classification System, NAICS',**

**'Location indicator - code',**--- 1 Rural, 2 Urban</br> 
**'Location indicator',**

'Incorporation status', --- Medium's are all incorporated

**'Reference year'**

**1. 'Total number of businesses'**

**2. 'Total revenue',** = Sales of goods and services + All other revenues</br> 

**3. 'Sales of goods and services ( percent of total revenue)',** = Sales of goods and services/Total revenue</br> 

**4. 'Total expenses',**</br> 

**5. 'Net Profit/Loss'**</br> 

**6. 'Cost of sales (direct expenses) (%)'**</br> 

**7. 'Operating expenses (indirect expenses) (%)'**</br>

**8. 'Total assets'** </br>

**9. 'Total current assets'**</br>

**10. 'Total liabilities'**</br> 

**11. 'Total current liabilities'**</br>

**12. 'Total equity'**</br>

**13. 'Debt to equity ratio (times)'** --- This ratio is calculated as (total liabilities) / (total equity). This is **a solvency ratio that indicates a firm’s ability to pay its long-term debts.** The lower the positive ratio, the more solvent the business. The debt to equity ratio also provides information on the capital structure of a business—the extent to which a firm’s capital is financed through debt. This ratio is relevant for all industries.</br>

**14. 'Current debt to equity (%)'** --- This ratio is calculated as (current liabilities * 100) / (equity). This percentage is a measure of liquidity, which indicates **a firm’s relative ability to pay its short-term debts**. The lower the positive ratio, the more liquid the business. This ratio also provides information on the capital structure of a business and the extent to which a firm’s capital is financed through current debt. This ratio is relevant for all industries.</br>

**15. 'Revenue to equity ratio (times)'** --- This ratio is calculated as (total revenue) / (equity). It indicates **the profitability of a business**, relating the total business revenue to the amount of investment incurred to earn this income. This ratio provides an indication of **the economic productivity of capital.**</br>

**16. 'Net profit to equity (%)'** --- This ratio is calculated as (net profit * 100) / (equity). This percentage indicates **the profitability of a business**. It relates the business income to the amount of investment committed to earning that income. This percentage is also known as “return on investment” or “return on equity.” The higher the ratio, the relatively better the profitability.</br>

**17. 'Gross margin (%)'** --- This margin is calculated as (sales of goods and services - costs of sales * 100) / (sales of goods and services). This percentage provides a relative **measure of the profitability** or profit margin.</br>

///

**'Return on total assets (%)'** --- This return is calculated as (net profit + interest and bank fees) * 100 / (total assets). Also known as “return on total investment,” it is **a relative measure of profitability** and is defined as the rate of return earned on the investment of total assets by a business. It reflects the combined effect of both the operating and the financing or investing activities of a business. The higher the percentage, the better the profitability.</br>

**'Collection period for accounts receivable (days)'** --- It is **the estimate of the average number of days it takes to collect receivables from the day of the transaction**. It is calculated as (accounts receivable) / (average daily revenue). Average daily revenue is calculated as (total revenue) / (365 days). This ratio measures liquidity by indicating the effectiveness of the credit and debt collection activities of the business. Increases in the collection period indicate an increasing time lag between credit sales and cash realization. This ratio is not very relevant for financial, construction and real estate industries. It can also be calculated as (365 days) / (accounts receivable turnover). Accounts receivable turnover is calculated as sales revenue (on account) / (average trade accounts receivable).</br>

**'Current ratio (times)'** --- This ratio indicates the firm’s **ability to pay liabilities with current assets.** It is calculated as (total current assets) / (total current liabilities). The larger the ratio, the more liquid the business. It is not very relevant for financial, construction and real estate industries. This ratio is also known as the working capital ratio.</br>

**'Net fixed assets to equity (%)'** --- This ratio is calculated as (net fixed assets * 100) / (equity). Net fixed assets represent **long-term investments**. This percentage indicates the relative capital investment structure.</br>

**'Interest coverage ratio (times)'** --- This ratio is calculated as (net profit + interest and bank fees) / (interest and bank fees). It represents the average number of times that interest owing is earned and, therefore, indicates **the debt risk of a business.** The larger the ratio, the more able a firm is to cover its interest obligations on the debt. This ratio is not very relevant for financial industries. It is also known as “times interest earned ratio.”</br>

**'Debt ratio (times)'** --- This ratio is calculated as (total liabilities) / (total assets). It is **a solvency ratio indicating a firm’s ability to pay its long-term debts**. It reports the amount of debt outstanding in relation to the amount of capital. The lower the ratio, the more solvent the business.</br>

**'Revenue to closing inventory ratio (times)'** --- This ratio is calculated as (total revenue) / (closing inventory). This is an efficiency ratio that indicates **the average liquidity of the inventory** or whether a business has over- or under-stocked inventory. This ratio is also known as “inventory turnover” and is often calculated using “cost of sales (direct expenses)” rather than “total revenue.” This ratio is not very relevant for financial, construction and real estate industries.</br>

### 2. Small business important variables 待梳理

**'North American Industry Classification System, NAICS - code',**</br> 
**'North American Industry Classification System, NAICS',**

**'Geography - code',** </br>
**'Geography',** --- Canada and provinces and territories

**'Location indicator - code',**--- 1 Rural, 2 Urban</br> 
**'Location indicator',**

**'Incorporation status - code',**---1: Unincorporated, ---2: incorporated </br> 
**'Incorporation status',** --- 3: All businesses

**'Reference year',**

**'Total number of businesses',**

**'Total revenue',** = Sales of goods and services + All other revenues</br> 

**'Sales of goods and services\*',**</br> 

**'All other revenues\*',**</br> 

**'Sales of goods and services\* ( percent of total revenue)',** = Sales of goods and services/Total revenue</br> 

**'All other revenues\* ( percent of total revenue)',** = All other revenues/Total revenue</br> 


Tab7

**'Percent of profitable businesses',**  

**'Profitable : Total Revenue',**- 'Profitable : Total Expenses' = 'Profitable : Net Profit'</br> 

**'Profitable : Total Expenses',**</br>

**'Profitable : Net Profit',**--- For profitable business</br> 

**'Non-profitable : Total Revenue',**- 'Non-profitable : Total expenses' = 'Non-profitable : Net loss'</br> 

**'Non-profitable : Total expenses',**</br>

**'Non-profitable : Net loss',** --- For non-profitable business</br>

## Data Cleaning

**Both for Medium and Small business Data**

### 1. Drop the first NAN row, drop quartile columns, select all industry code level and concat different years

In [6]:
# Drop the first NaN row, select all industry code level, drop quartile columns and concat different years
def selectData(tabs):
    concatTabs = []
    for tab in tabs:
        tab = tab.drop(0)
        cols_without_quartile = [x for x in tab.columns if 'quartile' not in x.lower() and 'reporting' not in x.lower()]
        tab = tab[cols_without_quartile]
        concatTabs.append(tab)
    return pd.concat(concatTabs)

In [7]:
## medium tab1-tab5 3year contain All industry(code=0)
mb_revenue_tab1_3y_pca = selectData([rcbp_2017_mb_revenue_Tabs[0], rcbp_2018_mb_revenue_Tabs[0], rcbp_2019_mb_revenue_Tabs[0]]).reset_index(drop=True)
mb_revenue_tab2_3y_pca = selectData([rcbp_2017_mb_revenue_Tabs[1], rcbp_2018_mb_revenue_Tabs[1], rcbp_2019_mb_revenue_Tabs[1]]).reset_index(drop=True)
mb_revenue_tab3_3y_pca = selectData([rcbp_2017_mb_revenue_Tabs[2], rcbp_2018_mb_revenue_Tabs[2], rcbp_2019_mb_revenue_Tabs[2]]).reset_index(drop=True)
mb_revenue_tab4_3y_pca = selectData([rcbp_2017_mb_revenue_Tabs[3], rcbp_2018_mb_revenue_Tabs[3], rcbp_2019_mb_revenue_Tabs[3]]).reset_index(drop=True)
mb_revenue_tab5_3y_pca = selectData([rcbp_2017_mb_revenue_Tabs[4], rcbp_2018_mb_revenue_Tabs[4], rcbp_2019_mb_revenue_Tabs[4]]).reset_index(drop=True)

## small tab1-tab7 3year contain All industry
sb_revenue_tab1_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[0], rcbp_2018_sb_revenue_Tabs[0], rcbp_2019_sb_revenue_Tabs[0]]).reset_index(drop=True)
sb_revenue_tab2_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[1], rcbp_2018_sb_revenue_Tabs[1], rcbp_2019_sb_revenue_Tabs[1]]).reset_index(drop=True)
sb_revenue_tab3_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[2], rcbp_2018_sb_revenue_Tabs[2], rcbp_2019_sb_revenue_Tabs[2]]).reset_index(drop=True)
sb_revenue_tab4_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[3], rcbp_2018_sb_revenue_Tabs[3], rcbp_2019_sb_revenue_Tabs[3]]).reset_index(drop=True)
sb_revenue_tab5_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[4], rcbp_2018_sb_revenue_Tabs[4], rcbp_2019_sb_revenue_Tabs[4]]).reset_index(drop=True)
sb_revenue_tab6_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[5], rcbp_2018_sb_revenue_Tabs[5], rcbp_2019_sb_revenue_Tabs[5]]).reset_index(drop=True)
sb_revenue_tab7_3y_pca = selectData([rcbp_2017_sb_revenue_Tabs[6], rcbp_2018_sb_revenue_Tabs[6], rcbp_2019_sb_revenue_Tabs[6]]).reset_index(drop=True)

In [8]:
len(mb_revenue_tab1_3y_pca) # same for Tab1-5

666

In [9]:
len(sb_revenue_tab3_3y_pca) # same for Tab1-3 32967

32967

In [10]:
len(sb_revenue_tab7_3y_pca) # same for Tab4-5,7 10989

10989

In [11]:
len(sb_revenue_tab6_3y_pca) # same for Tab6 21978

21978

### 2. Select Columns, Drop irrelevant columns

**mb_tab1: 'Total number of businesses', 'Total revenue', 'Sales of goods and services ( percent of total revenue)'**

In [12]:
mb_tab1_pca_left_col = ['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year', 
                        'Total number of businesses', 
                        'Total revenue',
                        'Sales of goods and services ( percent of total revenue)']
mb_revenue_tab1_3y_pca = mb_revenue_tab1_3y_pca[mb_tab1_pca_left_col]

In [13]:
mb_tab2_pca_left_col = ['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year', 
                        'Cost of sales (direct expenses) (%)', 
                        'Operating expenses (indirect expenses) (%)']
mb_revenue_tab2_3y_pca = mb_revenue_tab2_3y_pca[mb_tab2_pca_left_col]

In [14]:
mb_revenue_tab3_3y_pca.columns

Index(['ID', 'North American Industry Classification System, NAICS - code',
       'North American Industry Classification System, NAICS',
       'Geography - code', 'Geography', 'Location indicator - code',
       'Location indicator', 'Incorporation status - code',
       'Incorporation status', 'Reference year',
       'Cost of sales (direct expenses)',
       'Cost of sales (direct expenses), quality indicator',
       'Wages and benefits', 'Wages and benefits, quality indicator',
       'Purchases, materials and sub-contracts',
       'Purchases, materials and sub-contracts, quality indicator',
       'Opening inventory', 'Opening inventory, quality indicator',
       'Closing inventory', 'Closing inventory, quality indicator',
       'Operating expenses (indirect expenses)',
       'Operating expenses (indirect expenses), quality indicator',
       'Labour and commissions', 'Labour and commissions, quality indicator',
       'Amortization and depletion',
       'Amortization and depletion, quality indicator',
       'Repairs and maintenance', 'Repairs and maintenance, quality indicator',
       'Utilities and telephone/telecommunication',
       'Utilities and telephone/telecommunication, quality indicator', 'Rent',
       'Rent, quality indicator', 'Interest and bank charges',
       'Interest and bank charges, quality indicator',
       'Professional and business fees',
       'Professional and business fees, quality indicator',
       'Advertising and promotion',
       'Advertising and promotion, quality indicator',
       'Delivery, shipping and warehouse',
       'Delivery, shipping and warehouse, quality indicator', 'Insurance',
       'Insurance, quality indicator', 'Other indirect expenses',
       'Other indirect expenses, quality indicator', 'Total expenses',
       'Total expenses, quality indicator', 'Net Profit/Loss',
       'Net Profit/Loss, quality indicator'],
      dtype='object')

In [15]:
mb_tab3_pca_left_col = ['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year', 
                        'Total expenses',
                        'Cost of sales (direct expenses)',
                        'Operating expenses (indirect expenses)',
                        'Net Profit/Loss']
mb_revenue_tab3_3y_pca = mb_revenue_tab3_3y_pca[mb_tab3_pca_left_col]

In [16]:
mb_tab4_pca_left_col = ['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year', 
                        'Total assets', 
                        'Total current assets', 
                        'Total liabilities', 
                        'Total current liabilities', 
                        'Total equity']
mb_revenue_tab4_3y_pca = mb_revenue_tab4_3y_pca[mb_tab4_pca_left_col]

In [17]:
mb_tab5_pca_left_col = ['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year', 
                        'Debt to equity ratio (times)', 
                        'Current debt to equity (%)', 
                        'Revenue to equity ratio (times)', 
                        'Net profit to equity (%)', 
                        'Gross margin (%)']
mb_revenue_tab5_3y_pca = mb_revenue_tab5_3y_pca[mb_tab5_pca_left_col]

**Join the medium business tab1-tab5.**

In [18]:
a = pd.merge(mb_revenue_tab1_3y_pca,mb_revenue_tab2_3y_pca,how='inner',left_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'],right_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'])

In [19]:
b = pd.merge(a,mb_revenue_tab3_3y_pca,how='inner',left_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'],right_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'])

In [20]:
c = pd.merge(b,mb_revenue_tab4_3y_pca,how='inner',left_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'],right_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'])

In [21]:
final_table_mb = pd.merge(c,mb_revenue_tab5_3y_pca,how='inner',left_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'],right_on=['North American Industry Classification System, NAICS - code', 'North American Industry Classification System, NAICS',
                        'Location indicator - code', 'Location indicator', 'Reference year'])

In [22]:
final_table_mb.head(5)

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
0,0,All industries,1.0,Rural,2017.0,6901,9259.4,95.5,58.5,37.6,...,7255.4,3181.8,4064.8,2293.4,3190.6,1.3,71.9,2.9,11.4,38.7
1,0,All industries,2.0,Urban,2017.0,40390,9499.6,92.1,59.3,34.3,...,11645.7,4610.8,6135.9,3111,5509.8,1.1,56.5,1.7,11,35.6
2,11,"Agriculture, forestry, fishing and hunting",1.0,Rural,2017.0,1108,8615.9,93,18.2,92.6,...,10822.2,3764.2,6337.5,3141.1,4484.7,1.4,70,1.9,-20.7,80.5
3,11,"Agriculture, forestry, fishing and hunting",2.0,Urban,2017.0,835,8840.2,94.2,21.5,89.7,...,11223.4,3685.3,7437.1,3570.2,3786.3,2,94.3,2.3,-26.3,77.1
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3

In [23]:
len(final_table_mb)

666

In [24]:
new_mb = final_table_mb.replace(regex=['X', '\.\.', '\.\.\.'], value=np.nan)

In [25]:
new_mb = new_mb.dropna()

In [26]:
len(new_mb)

572

In [27]:
new_mb.head(10)

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
0,0,All industries,1.0,Rural,2017.0,6901,9259.4,95.5,58.5,37.6,...,7255.4,3181.8,4064.8,2293.4,3190.6,1.3,71.9,2.9,11.4,38.7
1,0,All industries,2.0,Urban,2017.0,40390,9499.6,92.1,59.3,34.3,...,11645.7,4610.8,6135.9,3111,5509.8,1.1,56.5,1.7,11,35.6
2,11,"Agriculture, forestry, fishing and hunting",1.0,Rural,2017.0,1108,8615.9,93,18.2,92.6,...,10822.2,3764.2,6337.5,3141.1,4484.7,1.4,70,1.9,-20.7,80.5
3,11,"Agriculture, forestry, fishing and hunting",2.0,Urban,2017.0,835,8840.2,94.2,21.5,89.7,...,11223.4,3685.3,7437.1,3570.2,3786.3,2,94.3,2.3,-26.3,77.1
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3
5,111,Crop production,2.0,Urban,2017.0,377,8660,94.2,11.5,100.8,...,11526.2,3766.6,7266.7,3265.5,4259.5,1.7,76.7,2,-24.9,87.8
6,112,Animal production and aquaculture,1.0,Rural,2017.0,377,8801.3,92.6,8.1,124.5,...,13637.2,4689.7,8716.7,4406.8,4920.5,1.8,89.6,1.8,-58.4,91.2
7,112,Animal production and aquaculture,2.0,Urban,2017.0,224,8622,93.7,6.6,124.6,...,15295.4,4661.9,10445.5,4741.5,4849.9,2.2,97.8,1.8,-55.5,93
9,113,Forestry and logging,2.0,Urban,2017.0,118,9326.2,98.2,55.5,36,...,5824.3,1730.5,3684,1943.4,2140.3,1.7,90.8,4.4,37,43.5
11,114,"Fishing, hunting and trapping",2.0,Urban,2017.0,14,10146.1,97.3,28.2,63.7,...,12597.8,3446.9,8182.5,3403.7,4415.2,1.9,77.1,2.3,18.6,71

In [28]:
new_mb.dtypes

North American Industry Classification System, NAICS - code     object
North American Industry Classification System, NAICS            object
Location indicator - code                                      float64
Location indicator                                              object
Reference year                                                 float64
Total number of businesses                                      object
Total revenue                                                   object
Sales of goods and services ( percent of total revenue)         object
Cost of sales (direct expenses) (%)                             object
Operating expenses (indirect expenses) (%)                      object
Total expenses                                                  object
Cost of sales (direct expenses)                                 object
Operating expenses (indirect expenses)                          object
Net Profit/Loss                                                 object
Total assets                                                    object
Total current assets                                            object
Total liabilities                                               object
Total current liabilities                                       object
Total equity                                                    object
Debt to equity ratio (times)                                    object
Current debt to equity (%)                                      object
Revenue to equity ratio (times)                                 object
Net profit to equity (%)                                        object
Gross margin (%)                                                object
dtype: object

In [29]:
new_mb[["Total number of businesses","Total revenue", "Sales of goods and services ( percent of total revenue)","Cost of sales (direct expenses) (%)",
        "Operating expenses (indirect expenses) (%)","Total expenses", 'Cost of sales (direct expenses)','Operating expenses (indirect expenses)',
        "Net Profit/Loss","Total assets","Total current assets","Total liabilities",
        "Total current liabilities","Total equity","Debt to equity ratio (times)","Current debt to equity (%)","Revenue to equity ratio (times)",
        "Net profit to equity (%)","Gross margin (%)"]] = new_mb[["Total number of businesses","Total revenue", 
                                                                  "Sales of goods and services ( percent of total revenue)","Cost of sales (direct expenses) (%)",
                                                                  "Operating expenses (indirect expenses) (%)","Total expenses",'Cost of sales (direct expenses)',
                                                                  'Operating expenses (indirect expenses)',"Net Profit/Loss","Total assets",
                                                                  "Total current assets","Total liabilities","Total current liabilities","Total equity",
                                                                  "Debt to equity ratio (times)","Current debt to equity (%)","Revenue to equity ratio (times)",
                                                                  "Net profit to equity (%)","Gross margin (%)"]].apply(pd.to_numeric)

In [30]:
new_mb.dtypes

North American Industry Classification System, NAICS - code     object
North American Industry Classification System, NAICS            object
Location indicator - code                                      float64
Location indicator                                              object
Reference year                                                 float64
Total number of businesses                                       int64
Total revenue                                                  float64
Sales of goods and services ( percent of total revenue)        float64
Cost of sales (direct expenses) (%)                            float64
Operating expenses (indirect expenses) (%)                     float64
Total expenses                                                 float64
Cost of sales (direct expenses)                                float64
Operating expenses (indirect expenses)                         float64
Net Profit/Loss                                                float64
Total assets                                                   float64
Total current assets                                           float64
Total liabilities                                              float64
Total current liabilities                                      float64
Total equity                                                   float64
Debt to equity ratio (times)                                   float64
Current debt to equity (%)                                     float64
Revenue to equity ratio (times)                                float64
Net profit to equity (%)                                       float64
Gross margin (%)                                               float64
dtype: object

In [31]:
new_mb.to_csv("new_mb.csv")

In [32]:
new_mb.shape

(572, 24)

In [33]:
new_mb.head(20)

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
0,0,All industries,1.0,Rural,2017.0,6901,9259.4,95.5,58.5,37.6,...,7255.4,3181.8,4064.8,2293.4,3190.6,1.3,71.9,2.9,11.4,38.7
1,0,All industries,2.0,Urban,2017.0,40390,9499.6,92.1,59.3,34.3,...,11645.7,4610.8,6135.9,3111.0,5509.8,1.1,56.5,1.7,11.0,35.6
2,11,"Agriculture, forestry, fishing and hunting",1.0,Rural,2017.0,1108,8615.9,93.0,18.2,92.6,...,10822.2,3764.2,6337.5,3141.1,4484.7,1.4,70.0,1.9,-20.7,80.5
3,11,"Agriculture, forestry, fishing and hunting",2.0,Urban,2017.0,835,8840.2,94.2,21.5,89.7,...,11223.4,3685.3,7437.1,3570.2,3786.3,2.0,94.3,2.3,-26.3,77.1
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3
5,111,Crop production,2.0,Urban,2017.0,377,8660.0,94.2,11.5,100.8,...,11526.2,3766.6,7266.7,3265.5,4259.5,1.7,76.7,2.0,-24.9,87.8
6,112,Animal production and aquaculture,1.0,Rural,2017.0,377,8801.3,92.6,8.1,124.5,...,13637.2,4689.7,8716.7,4406.8,4920.5,1.8,89.6,1.8,-58.4,91.2
7,112,Animal production and aquaculture,2.0,Urban,2017.0,224,8622.0,93.7,6.6,124.6,...,15295.4,4661.9,10445.5,4741.5,4849.9,2.2,97.8,1.8,-55.5,93.0
9,113,Forestry and logging,2.0,Urban,2017.0,118,9326.2,98.2,55.5,36.0,...,5824.3,1730.5,3684.0,1943.4,2140.3,1.7,90.8,4.4,37.0,43.5
11,114,"Fishing, hunting and trapping",2.0,Urban,2017.0,14,10146.1,97.3,28.2,63.7,...,12597.8,3446.9,8182.5,3403.7,4415.2,1.9,77.1,2.3,18.6,71.0
12,115,Support activities for agriculture and forestry,1.0,Rural,2017.0,81,9290.7,94.4,54.4,41.7,...,5221.8,2897.1,3066.8,2123.9,2155.0,1.4,98.6,4.3,16.7,42.3
13,115,Support activities for agriculture and forestry,2.0,Urban,2017.0,102,9243.7,89.8,46.2,46.8,...,7219.1,3533.9,5699.9,4029.3,1519.2,3.8,265.2,6.1,42.6,48.5
14,21,"Mining, quarrying, and oil and gas extraction",1.0,Rural,2017.0,131,9178.2,97.9,41.4,48.9,...,9928.2,3371.5,6166.8,2934.7,3761.4,1.6,78.0,2.4,23.7,57.7
15,21,"Mining, quarrying, and oil and gas extraction",2.0,Urban,2017.0,385,10134.1,89.5,46.9,80.1,...,37954.3,7119.0,16853.7,7676.8,21100.6,0.8,36.4,0.5,-13.0,47.6
17,211,Oil and gas extraction,2.0,Urban,2017.0,86,10536.9,86.8,42.2,194.6,...,73385.7,11559.6,35929.0,18849.9,37456.6,1.0,50.3,0.3,-38.5,51.4
19,212,Mining and quarrying (except oil and gas),2.0,Urban,2017.0,71,10762.5,95.6,62.1,37.4,...,24281.5,8052.7,9739.4,6042.6,14542.1,0.7,41.6,0.7,0.4,35.0
20,213,"Support activities for mining, and oil and gas...",1.0,Rural,2017.0,90,8878.1,98.3,35.4,54.5,...,7077.6,2863.9,4794.6,2667.9,2283.0,2.1,116.9,3.9,39.5,64.0
21,213,"Support activities for mining, and oil and gas...",2.0,Urban,2017.0,228,9786.5,88.5,43.6,48.2,...,28847.5,5153.3,11874.0,3971.3,16973.5,0.7,23.4,0.6,4.7,50.7
22,22,Utilities,1.0,Rural,2017.0,34,8889.3,91.5,50.5,47.3,...,37058.3,5047.8,17819.3,8828.4,19239.0,0.9,45.9,0.5,1.0,44.8
23,22,Utilities,2.0,Urban,2017.0,70,9957.1,90.5,39.2,52.6,...,33397.3,7767.3,20560.2,6337.7,12837.1,1.6,49.4,0.8,6.3,56.6

**This is the end of medium business column**

In [34]:
new_mb

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
0,0,All industries,1.0,Rural,2017.0,6901,9259.4,95.5,58.5,37.6,...,7255.4,3181.8,4064.8,2293.4,3190.6,1.3,71.9,2.9,11.4,38.7
1,0,All industries,2.0,Urban,2017.0,40390,9499.6,92.1,59.3,34.3,...,11645.7,4610.8,6135.9,3111.0,5509.8,1.1,56.5,1.7,11.0,35.6
2,11,"Agriculture, forestry, fishing and hunting",1.0,Rural,2017.0,1108,8615.9,93.0,18.2,92.6,...,10822.2,3764.2,6337.5,3141.1,4484.7,1.4,70.0,1.9,-20.7,80.5
3,11,"Agriculture, forestry, fishing and hunting",2.0,Urban,2017.0,835,8840.2,94.2,21.5,89.7,...,11223.4,3685.3,7437.1,3570.2,3786.3,2.0,94.3,2.3,-26.3,77.1
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,81,Other services (except public administration),2.0,Urban,2019.0,1288,8752.7,67.9,36.5,56.0,...,10996.7,4662.3,4595.6,2851.6,6401.1,0.7,44.5,1.4,10.3,46.3
658,811,Repair and maintenance,1.0,Rural,2019.0,98,8330.6,99.0,64.2,27.7,...,4551.1,2854.3,2611.7,1775.4,1939.4,1.3,91.5,4.3,34.8,35.1
659,811,Repair and maintenance,2.0,Urban,2019.0,587,8420.9,97.7,62.0,30.5,...,5155.5,3042.8,2986.7,1748.7,2168.8,1.4,80.6,3.9,29.4,36.6
662,813,"Religious, grant-making, civic, and profession...",1.0,Rural,2019.0,24,9912.5,44.1,16.5,61.4,...,17274.5,5092.5,2749.5,1465.9,14525.0,0.2,10.1,0.7,15.1,62.6
663,813,"Religious, grant-making, civic, and profession...",2.0,Urban,2019.0,529,9117.0,29.4,9.8,82.6,...,18216.8,7022.2,5831.2,4212.7,12385.7,0.5,34.0,0.7,5.6,66.6

In [35]:
new_mb_3dig_ind = new_mb.loc[(new_mb["North American Industry Classification System, NAICS - code"].str.len() == 3)]

In [36]:
new_mb_3dig_ind

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3
5,111,Crop production,2.0,Urban,2017.0,377,8660.0,94.2,11.5,100.8,...,11526.2,3766.6,7266.7,3265.5,4259.5,1.7,76.7,2.0,-24.9,87.8
6,112,Animal production and aquaculture,1.0,Rural,2017.0,377,8801.3,92.6,8.1,124.5,...,13637.2,4689.7,8716.7,4406.8,4920.5,1.8,89.6,1.8,-58.4,91.2
7,112,Animal production and aquaculture,2.0,Urban,2017.0,224,8622.0,93.7,6.6,124.6,...,15295.4,4661.9,10445.5,4741.5,4849.9,2.2,97.8,1.8,-55.5,93.0
9,113,Forestry and logging,2.0,Urban,2017.0,118,9326.2,98.2,55.5,36.0,...,5824.3,1730.5,3684.0,1943.4,2140.3,1.7,90.8,4.4,37.0,43.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,722,Food services and drinking places,2.0,Urban,2019.0,1392,8433.7,98.5,45.4,50.1,...,3856.9,1289.2,2589.3,1563.7,1267.6,2.0,123.4,6.7,29.7,53.9
658,811,Repair and maintenance,1.0,Rural,2019.0,98,8330.6,99.0,64.2,27.7,...,4551.1,2854.3,2611.7,1775.4,1939.4,1.3,91.5,4.3,34.8,35.1
659,811,Repair and maintenance,2.0,Urban,2019.0,587,8420.9,97.7,62.0,30.5,...,5155.5,3042.8,2986.7,1748.7,2168.8,1.4,80.6,3.9,29.4,36.6
662,813,"Religious, grant-making, civic, and profession...",1.0,Rural,2019.0,24,9912.5,44.1,16.5,61.4,...,17274.5,5092.5,2749.5,1465.9,14525.0,0.2,10.1,0.7,15.1,62.6
663,813,"Religious, grant-making, civic, and profession...",2.0,Urban,2019.0,529,9117.0,29.4,9.8,82.6,...,18216.8,7022.2,5831.2,4212.7,12385.7,0.5,34.0,0.7,5.6,66.6

In [37]:
new_mb_3dig_ind.shape

(458, 24)

In [38]:
new_mb_3dig_ind.to_csv("new_mb_3dig_ind.csv")

In [39]:
new_mb_2dig_ind = new_mb.loc[(new_mb["North American Industry Classification System, NAICS - code"].str.len() == 2) |
                             (new_mb["North American Industry Classification System, NAICS - code"].str.contains('-'))]

In [40]:
new_mb_2dig_ind.shape

(108, 24)

In [41]:
458+108

566

In [47]:
new_mb_2dig_ind.to_csv("new_mb_2dig_ind.csv")

In [49]:
new_mb_pca = new_mb.dropna()

In [50]:
new_mb_pca

,"North American Industry Classification System, NAICS - code","North American Industry Classification System, NAICS",Location indicator - code,Location indicator,Reference year,Total number of businesses,Total revenue,Sales of goods and services ( percent of total revenue),Cost of sales (direct expenses) (%),Operating expenses (indirect expenses) (%),...,Total assets,Total current assets,Total liabilities,Total current liabilities,Total equity,Debt to equity ratio (times),Current debt to equity (%),Revenue to equity ratio (times),Net profit to equity (%),Gross margin (%)
0,0,All industries,1.0,Rural,2017.0,6901,9259.4,95.5,58.5,37.6,...,7255.4,3181.8,4064.8,2293.4,3190.6,1.3,71.9,2.9,11.4,38.7
1,0,All industries,2.0,Urban,2017.0,40390,9499.6,92.1,59.3,34.3,...,11645.7,4610.8,6135.9,3111.0,5509.8,1.1,56.5,1.7,11.0,35.6
2,11,"Agriculture, forestry, fishing and hunting",1.0,Rural,2017.0,1108,8615.9,93.0,18.2,92.6,...,10822.2,3764.2,6337.5,3141.1,4484.7,1.4,70.0,1.9,-20.7,80.5
3,11,"Agriculture, forestry, fishing and hunting",2.0,Urban,2017.0,835,8840.2,94.2,21.5,89.7,...,11223.4,3685.3,7437.1,3570.2,3786.3,2.0,94.3,2.3,-26.3,77.1
4,111,Crop production,1.0,Rural,2017.0,428,8132.5,89.9,8.7,100.5,...,12045.7,4228.1,6595.3,3110.9,5450.4,1.2,57.1,1.5,-13.7,90.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,81,Other services (except public administration),2.0,Urban,2019.0,1288,8752.7,67.9,36.5,56.0,...,10996.7,4662.3,4595.6,2851.6,6401.1,0.7,44.5,1.4,10.3,46.3
658,811,Repair and maintenance,1.0,Rural,2019.0,98,8330.6,99.0,64.2,27.7,...,4551.1,2854.3,2611.7,1775.4,1939.4,1.3,91.5,4.3,34.8,35.1
659,811,Repair and maintenance,2.0,Urban,2019.0,587,8420.9,97.7,62.0,30.5,...,5155.5,3042.8,2986.7,1748.7,2168.8,1.4,80.6,3.9,29.4,36.6
662,813,"Religious, grant-making, civic, and profession...",1.0,Rural,2019.0,24,9912.5,44.1,16.5,61.4,...,17274.5,5092.5,2749.5,1465.9,14525.0,0.2,10.1,0.7,15.1,62.6
663,813,"Religious, grant-making, civic, and profession...",2.0,Urban,2019.0,529,9117.0,29.4,9.8,82.6,...,18216.8,7022.2,5831.2,4212.7,12385.7,0.5,34.0,0.7,5.6,66.6

In [51]:
new_mb_pca.to_csv("new_mb_pca.csv")